hepsi:derle calistir

derle:
	gcc -I ./include/ -c ./src/main.c -o ./lib/main.o
	gcc -I ./include/ -c ./src/proje.c -o ./lib/proje.o
	gcc -I ./include/ -o ./bin/main ./lib/*.o
calistir:
	./bin/main